### PR TITLE
✨ Update golangci-lint version and fix related linting issues

### LINKED ISSUE #300: golangci-lint failing on PRs
**Which jobs are failing:**

golangci-lint / lint https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm/actions/runs/11438987508/job/31821729558?pr=297 for example

**Which tests are failing:**

Many `typecheck` linter errors which appear to be false positives.

**Since when has it been failing:**

At least two weeks.

/kind failing-test

### PR DESCRIPTION
**Pull request by thiha-min-thant**
- Bumped golangci-lint to v1.61.0 to ensure compatibility with recent code updates and improve linting accuracy.
- Addressed the following linting issues:
  - S1009: Removed unnecessary nil check (gosimple).
  - Printf: Resolved govet error by handling a non-constant format string in function call.

**What this PR does / why we need it**: This PR updates golangci-lint to the latest compatible version and resolves existing linting errors that were affecting pull requests. By addressing these issues, we maintain code quality and ensure smooth CI checks.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #300

### CODE REVIEW

**Comment by thiha-min-thant** [comment]
Hi @mboersma, could you please review this PR? Thanks!

File: controllers/helmreleaseproxy/helmreleaseproxy_controller.go [hunk 1]
```diff
@@ -156,7 +156,7 @@ func (r *HelmReleaseProxyReconciler) Reconcile(ctx context.Context, req ctrl.Req
 				restConfig, err := remote.RESTConfig(ctx, "caaph", r.Client, clusterKey)
 				if err != nil {
 					wrappedErr := errors.Wrapf(err, "failed to get kubeconfig for cluster")
-					conditions.MarkFalse(helmReleaseProxy, addonsv1alpha1.ClusterAvailableCondition, addonsv1alpha1.GetKubeconfigFailedReason, clusterv1.ConditionSeverityError, wrappedErr.Error())
+					conditions.MarkFalse(helmReleaseProxy, addonsv1alpha1.ClusterAvailableCondition, addonsv1alpha1.GetKubeconfigFailedReason, clusterv1.ConditionSeverityError, "failed to get kubeconfig for cluster")
```
Comment (mboersma) [inline controllers/helmreleaseproxy/helmreleaseproxy_controller.go:159]: This could lose some information by not getting the string directly from the `wrappedErr`, and introduces the potential for the two strings with the same error message to disagree. Would it be better to use a temp variable like `errMsg := wrappedErr.Error()` to work around the linter, or just do `//nolint:govet` for these?

**Comment by thiha-min-thant** [comment]
Hi @mboersma, I refactored error handling. PTAL. Thanks!

**Review by mboersma — APPROVED** [review]
/lgtm
/assign @Jont828 

Thanks @thiha-min-thant!
